buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        google()
        gradlePluginPortal()
        maven { url = 'https://oss.sonatype.org/content/repositories/snapshots/' }
        maven { url = 'https://jitpack.io' }
    }
    dependencies {
        //classpath "com.android.tools.build:gradle:$gradleVersion"
        // AGP Update Assistant needs this version numbers here, not in gradle.properties
        classpath 'com.android.tools.build:gradle:8.11.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath "org.wisepersist:gwt-gradle-plugin:$gwtPluginVersion"
        classpath "com.mobidevelop.robovm:robovm-gradle-plugin:$roboVMVersion"
        classpath "space.earlygrey:shapedrawer:$shapedrawerVersion"
        classpath "org.mini2Dx:universal-tween-engine:$tweenEngineVersion"
    }
}

plugins {
    id 'org.jetbrains.kotlin.jvm' version "$kotlinVersion"
}

allprojects {
    apply plugin: 'eclipse'
    apply plugin: 'idea'

    version = '1.16'
    ext.appName = 'Tangler'
    repositories {
        mavenLocal()
        mavenCentral()
        google()
        gradlePluginPortal()
        maven { url = 'https://oss.sonatype.org/content/repositories/snapshots/' }
        maven { url = 'https://oss.sonatype.org/content/repositories/releases/' }
        maven { url = 'https://jitpack.io' }
    }
}

eclipse.project.name = 'Tangler' + '-parent'
